use crate::ensure_config_dir;
use crate::error::{PrismError, PrismResult};
use crate::themes::{ScriptAsset, Theme};
use std::fs;
use std::path::Path;

pub fn apply_theme(theme: &Theme) -> PrismResult<()> {
    let config_dir = ensure_config_dir()?;

    // Apply for each shell
    apply_for_shell(theme, "zsh", &config_dir)?;
    apply_for_shell(theme, "bash", &config_dir)?;
    apply_for_shell(theme, "fish", &config_dir)?;

    Ok(())
}

fn apply_for_shell(theme: &Theme, shell: &str, config_dir: &Path) -> PrismResult<()> {
    let target_path = config_dir.join(format!("prism.{}", shell));

    // Get the asset for this shell
    let asset = match shell {
        "zsh" => &theme.scripts.zsh,
        "bash" => &theme.scripts.bash,
        "fish" => &theme.scripts.fish,
        _ => return Ok(()), // Should not happen
    };

    match asset {
        ScriptAsset::File(path) => {
            // If it's a specific file, we copy it directly
            if path.exists() {
                fs::copy(path, &target_path)?;
            } else {
                // Fallback if file missing?
                return Err(PrismError::new(format!(
                    "Theme script missing: {}",
                    path.display()
                )));
            }
        }
        ScriptAsset::Template(_) => {
            // If it's a template, we generate the script from the palette
            let content = generate_script(theme, shell)?;
            fs::write(&target_path, content)?;
        }
    }

    Ok(())
}

fn generate_script(theme: &Theme, shell: &str) -> PrismResult<String> {
    // Map palette to variables
    // We assume accents[0] is primary, [1] secondary, [2] accent
    // If not present, fallback to base colors
    let p = &theme.palette;
    let primary = p.accents.first().unwrap_or(&p.base[0]);
    let secondary = p.accents.get(1).unwrap_or(&p.base[1]);
    let accent = p.accents.get(2).unwrap_or(&p.base[2]);

    // Simple mappings for error/success if not explicit (using red/green from base if standard)
    // Assuming base 16 standard: 0-7 normal, 8-15 bright.
    // usually 1=red, 2=green.
    let error = p.base.get(1).unwrap_or(primary);
    let success = p.base.get(2).unwrap_or(secondary);
    let fg = p.foreground.as_ref().unwrap_or(&p.base[7]); // Default to white/gray

    match shell {
        "zsh" => Ok(format!(
            r#"# Generated by Prism for theme: {}
prism_prompt() {{
  local primary='%F{{{}}}'
  local secondary='%F{{{}}}'
  local accent='%F{{{}}}'
  local fg='%F{{{}}}'
  local error='%F{{{}}}'
  local success='%F{{{}}}'
  
  local exit_status=$?
  local status_color=$success
  if [[ $exit_status -ne 0 ]]; then
    status_color=$error
  fi
  
  local branch=$(git -C "$PWD" symbolic-ref --short HEAD 2>/dev/null)
  local dirty=$(git -C "$PWD" status --porcelain 2>/dev/null)
  local git_line=""
  if [[ -n $branch ]]; then
    git_line="✦ ${{branch}}${{dirty:+ ⚡}}"
  fi
  
  PS1="${{primary}}%n@%m ${{secondary}}» ${{accent}}%~"
  PS1+="\n${{secondary}}${{git_line:+${{git_line}} }}${{status_color}}${{exit_status}} ${{primary}}› ${{fg}}"
}}
autoload -U add-zsh-hook
add-zsh-hook precmd prism_prompt
"#,
            theme.meta.name, primary, secondary, accent, fg, error, success
        )),
        "bash" => Ok(format!(
            r#"# Generated by Prism for theme: {}
prism_prompt() {{
    local exit_status=$?
    # Colors
    local C_PRIMARY="\[\e[38;2;{};{};{}m\]"
    local C_SECONDARY="\[\e[38;2;{};{};{}m\]"
    local C_ACCENT="\[\e[38;2;{};{};{}m\]"
    local C_FG="\[\e[38;2;{};{};{}m\]"
    local C_RESET="\[\e[0m\]"
    
    PS1="${{C_PRIMARY}}\u@\h ${{C_SECONDARY}}» ${{C_ACCENT}}\w ${{C_RESET}}\n${{C_PRIMARY}}› ${{C_FG}}"
}}
PROMPT_COMMAND=prism_prompt
"#,
            theme.meta.name,
            hex_r(primary),
            hex_g(primary),
            hex_b(primary),
            hex_r(secondary),
            hex_g(secondary),
            hex_b(secondary),
            hex_r(accent),
            hex_g(accent),
            hex_b(accent),
            hex_r(fg),
            hex_g(fg),
            hex_b(fg)
        )),
        "fish" => Ok(format!(
            r#"# Generated by Prism for theme: {}
function fish_prompt
    set -l last_status $status
    set -l primary {}
    set -l secondary {}
    set -l accent {}
    set -l fg {}
    
    string join '' -- (set_color $primary) $USER @ (prompt_hostname) ' ' (set_color $secondary) '» ' (set_color $accent) (prompt_pwd)
    echo
    string join '' -- (set_color $primary) '› ' (set_color $fg)
end
"#,
            theme.meta.name,
            primary.replace("#", ""),
            secondary.replace("#", ""),
            accent.replace("#", ""),
            fg.replace("#", "")
        )),
        _ => Ok(String::new()),
    }
}

fn hex_r(hex: &str) -> u8 {
    u8::from_str_radix(&hex.trim_start_matches('#')[0..2], 16).unwrap_or(0)
}
fn hex_g(hex: &str) -> u8 {
    u8::from_str_radix(&hex.trim_start_matches('#')[2..4], 16).unwrap_or(0)
}
fn hex_b(hex: &str) -> u8 {
    u8::from_str_radix(&hex.trim_start_matches('#')[4..6], 16).unwrap_or(0)
}
