use std::fmt::{self, Display};

use serde::{Deserialize, Serialize};

use crate::core::theme::Theme;

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum PromptStyle {
    #[default]
    Minimal,
    Powerline,
    Rich,
}

impl Display for PromptStyle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PromptStyle::Minimal => write!(f, "minimal"),
            PromptStyle::Powerline => write!(f, "powerline"),
            PromptStyle::Rich => write!(f, "rich"),
        }
    }
}

pub fn generate_zsh(theme: &Theme) -> String {
    prompt_body("zsh", theme)
}

pub fn generate_bash(theme: &Theme) -> String {
    prompt_body("bash", theme)
}

pub fn generate_fish(theme: &Theme) -> String {
    prompt_body("fish", theme)
}

fn prompt_body(shell: &str, theme: &Theme) -> String {
    let mut segments = vec![];
    for (name, segment) in &theme.prompt.segments {
        let icon = segment.icon.clone().unwrap_or_default();
        segments.push(format!(
            "# segment {name}\nprism_segment_{name}() {{ echo '%{{{{{fg}-{bg}}}}}{icon}{{{{reset}}}}' ; }}",
            fg = segment.fg,
            bg = segment.bg
        ));
        if !icon.is_empty() {
            segments.push(format!("# icon for {name}: {icon}"));
        }
    }

    format!(
        "# Generated by IRIDEX ({shell})\n# Style: {}\n{}\n# TODO: implement shell-specific prompt injection\n",
        theme.prompt.style,
        segments.join("\n")
    )
}
