use std::fmt::{self, Display};
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::core::theme::Theme;
use crate::prompt_stream::{fallback_prompt, stream_path_from_config};

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[serde(rename_all = "lowercase")]
pub enum PromptStyle {
    #[default]
    Minimal,
    Powerline,
    Rich,
}

impl Display for PromptStyle {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            PromptStyle::Minimal => write!(f, "minimal"),
            PromptStyle::Powerline => write!(f, "powerline"),
            PromptStyle::Rich => write!(f, "rich"),
        }
    }
}

pub fn generate_zsh(theme: &Theme, config_dir: &Path) -> String {
    let stream_path = stream_path_from_config(config_dir);
    let fallback = escape_double_quotes(&fallback_prompt(theme));
    format!(
        r#"# Generated by IRIDEX (zsh)
prism_prompt_stream="{path}"
__prism_prompt_line() {{
    if [ -f "$prism_prompt_stream" ]; then
        cat "$prism_prompt_stream"
    else
        echo "{fallback}"
    fi
}}
PROMPT='$(__prism_prompt_line)'
"#,
        path = shell_path(&stream_path),
        fallback = fallback
    )
}

pub fn generate_bash(theme: &Theme, config_dir: &Path) -> String {
    let stream_path = stream_path_from_config(config_dir);
    let fallback = escape_double_quotes(&fallback_prompt(theme));
    format!(
        r#"# Generated by IRIDEX (bash)
prism_prompt_stream="{path}"
__prism_prompt_line() {{
    if [ -f "$prism_prompt_stream" ]; then
        cat "$prism_prompt_stream"
    else
        echo "{fallback}"
    fi
}}
__prism_prompt_command() {{
    PS1="$(__prism_prompt_line) "
}}
if [[ "$PROMPT_COMMAND" == *"__prism_prompt_command"* ]]; then
    :
else
    if [ -n "$PROMPT_COMMAND" ]; then
        PROMPT_COMMAND="__prism_prompt_command;$PROMPT_COMMAND"
    else
        PROMPT_COMMAND="__prism_prompt_command"
    fi
fi
"#,
        path = shell_path(&stream_path),
        fallback = fallback
    )
}

pub fn generate_fish(theme: &Theme, config_dir: &Path) -> String {
    let stream_path = stream_path_from_config(config_dir);
    let fallback = fallback_prompt(theme).replace('"', "\\\"");
    format!(
        r#"# Generated by IRIDEX (fish)
set -gx prism_prompt_stream "{path}"
function __prism_prompt_line
    if test -f $prism_prompt_stream
        cat $prism_prompt_stream
    else
        echo "{fallback}"
    end
end
if functions -q fish_prompt
    functions -c fish_prompt prism_original_prompt
end
function fish_prompt
    __prism_prompt_line
end
"#,
        path = shell_path(&stream_path),
        fallback = fallback
    )
}

fn escape_double_quotes(input: &str) -> String {
    input.replace('"', "\\\"")
}

fn shell_path(path: &Path) -> String {
    let raw = path.to_string_lossy();
    raw.replace('"', "\\\"")
}
